
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://mark-support.github.io/beyond-human-nature"

# If you're hosting your site at a Project repository on GitHub pages
# (https://mark-support.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /beyond-human-nature

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "StoryFirst Media"
title: "Beyond Human Nature"
description: "The story of the notorious 1992 Tom Monfils murder investigation and the townsfolk defined by it."
keywords: "neelsen, Monfils, beyond human nature, film, wisconsin, green bay, vat, paper mill, murder"
favicon: "/img/logo-bhn.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/crew-blur.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Who killed Tom Monfils?"
  - text: "The story of the notorious 1992 Tom Monfils murder investigation and the townsfolk defined by it."


me-img: "/img/logo-bhn.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: True
vkontakte-share: False

disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 1969, night"
    description: "We heard a crime [go](http://smile.amazon.com/The-Monfils-Conspiracy-Conviction-Innocent/dp/0595484735?sa-no-redirect=1)."

  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Filming begins"

  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Launch of Kickstarter campaign"

  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "That's a Wrap!"

  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Wiscosin premiere."

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "info@beyondhumannature.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "The film's director Michael Neelsen is a filmmaker, owner of StoryFirst Media, and host of the ReelFanatics podcast.

."
author_blurb_image: "https://pbs.twimg.com/profile_images/662700907621052416/q9IvCeP6_400x400.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/Beyond-Human-Nature-312071642313989/"
  - title: "twitter"
    url: "https://twitter.com/MichaelNeelsen"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Trailer: 'trailer'
  About: 'about'
  Production Diary: 'latest-post'
  Dates: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
